# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  worlds:                                                                      #
#    WorldName:                                                                 #
#      spawns:                                                                  #
#      - x,y,z                                                                  #
#      barriers:                                                                #
#      - x1,y1,z1 x2,y2,z2                                                      #
#      shops: - requires exact item frame location (use the provided command)   #
#      - x.xxxxx,y.yyyyyy,z.zzzzzz price                                        #
#      gate: x1,y1,z1 x2,y2,z2 MATERIALS                                        #
#      # material* = add materials containing this word                         #
#      # -material = remove all materials from the saved containing this word   #
#      chest: x,y,z                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
worlds:
  world:
    spawns:
    barriers:
    shops:
    gate:
    chest: