name: CODMinigame
version: 1.0
authors: [ Atomiz, Fen ]
main: me.atomiz.codminigame.Main
depend: [ Essentials, Vault ]
load: POSTWORLD
commands:
  codm:
    description: Main CODMinigame command
    aliases: codm
    permission: codm
permissions:
  codm:
    description: Access to all CODMinigame commands
    default: op